server:
  port: 8888
  servlet:
    context-path: /commodity_management_system
  tomcat:
    #设定Http form数据大小
    max-http-form-post-size: 102400000
    #设定Httppost数据大小
    max-http-post-size: 102400000
    #设定HttpHeader请求头大小
    max-http-header-size: 102400000

spring:
  output:
    ansi:
      enabled: always
    profiles:
      active: dev
    thymeleaf:
      encoding: UTF-8
      prefix: classpath:/templates/
  servlet:
    multipart:
        enabled: true
        #上传文件的大小限定；只有上传采用文件格式进行接收时起作用，针对上面的base64格式图片（后台是String进行接收）不起作用；
        max-file-size: 20MB
        #上传请求数据的大小限定；限定请求的总数据大小
        max-request-size: 20MB
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.219.151:3306/commodity_management_system?useSSL=false&serverTimezone=UTC
    username: root
    password: 6210

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

