server:
  port: 8888
  servlet:
    context-path: /CommodityMannagentSystem

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8
    username: root
    password: 6210
